services:
  postgres:
    container_name: postgres_go
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass_top
      PGDATA: /data/postgres
    volumes:
      - ./postgres_data:/data/postgres
    ports:
      - "5432:5432"